version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: hr
      POSTGRES_USER: hruser
      POSTGRES_PASSWORD: hrpass
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - '8000:8000'
    environment:
      DATABASE_URL: postgres://hruser:hrpass@db:5432/hr
    depends_on:
      - db

volumes:
  db_data:

